version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
 #   volumes:
  #    - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"

  superhero-service:
    container_name: smdc-crud-superhero-service
    build: superhero-service
    image: superhero-service
    depends_on:
      - mongo
   # hostname: localhost
    restart: always
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"
networks:
   default:
    name: myapp-network