
server:
    port: 8080
spring:
    data:
        mongodb:
            host: mongo
            port: 27017
            database: spring_boot_mongo_app
    application:
        name: superhero-service
